- name: Install OpenVPN using angristan/openvpn-install
  hosts: vpn_servers
  become: yes

  tasks:
    - name: Download script
      get_url:
        url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
        dest: /tmp/openvpn-install.sh
        mode: '0755'

    - name: Run script with environment variables
      shell: |
        /bin/bash /tmp/openvpn-install.sh \
        --country "US" \
        --state "New York" \
        --city "New York" \
        --org "Example Inc" \
        --email "user@example.com" \
        --server "tcp" \
        --port "1194" \
        --proto "udp" \
        --cipher "AES-256-CBC" \
        --auth "SHA256" \
        --keysize "2048" \
        --key-expire "3650" \
        --dns "8.8.8.8 8.8.4.4"
        # Добавьте сюда другие необходимые параметры
      #environment:
        # Здесь укажите переменные окружения, если они нужны
        # Например:
        #   MY_VARIABLE: "value"