---
- name: Converge
  hosts: vpn_servers
  become: true
  gather_facts: true

  tasks:
    - name: Create openvpn server
      ansible.builtin.include_role:
        name: ../roles/service_openvpn
      vars:
        openvpn_role: "server"

    - name: Copy certificates and keys from the server to the client
      ansible.builtin.copy:
        src: /etc/openvpn/easy-rsa/pki/{{ item }}
        dest: /home/vpnadmin/default_ovpn/{{ item | basename }}
        mode: "0640"
        remote_src: true
      loop:
        - ca.crt
        - issued/client.crt
        - private/client.key
        - ta.key
